"""update articles schema for frontend

Revision ID: 0465de7813f5
Revises: b24061b279fa
Create Date: 2026-05-05 20:05:25.302180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0465de7813f5'
down_revision: Union[str, Sequence[str], None] = 'b24061b279fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('slug', sa.String(length=255), nullable=False, comment='Уникальный URL'))
    op.add_column('articles', sa.Column('image', sa.String(length=1024), nullable=True))
    op.add_column('articles', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_column('articles', 'description')
    op.drop_column('articles', 'author')
    op.drop_column('articles', 'date')
    op.drop_column('articles', 'image')
    op.drop_column('articles', 'slug')
    # ### end Alembic commands ###
