"""update news schema with slug and enum

Revision ID: b24061b279fa
Revises: 8a7b6c5d4e3f
Create Date: 2026-05-04 20:02:45.639181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24061b279fa'
down_revision: Union[str, Sequence[str], None] = '8a7b6c5d4e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Явно создаем тип ENUM в PostgreSQL перед тем, как добавлять колонку
    from sqlalchemy.dialects import postgresql
    postgresql.ENUM('Анонс мероприятия', 'Отчет о мероприятии', name='newstype').create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_audit_logs_application_id'), table_name='application_audit_logs')
    op.drop_table('application_audit_logs')
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('appointments', sa.Column('conclusion', sa.String(length=2048), nullable=True, comment='Заключение психолога'))
    op.add_column('news', sa.Column('slug', sa.String(length=255), nullable=False, comment='Уникальный URL'))
    op.add_column('news', sa.Column('image', sa.String(length=1024), nullable=True, comment='Ссылка на картинку'))
    op.add_column('news', sa.Column('type', sa.Enum('ANNOUNCEMENT', 'REPORT', name='newstype'), nullable=True, comment='Тип новости'))
    op.add_column('news', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('news', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('link', sa.String(length=1024), nullable=True))
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Заголовок новости',
               existing_nullable=False)
    op.alter_column('news', 'text',
               existing_type=sa.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='Текст новости')
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.drop_column('news', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Дата и время создания'))
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.alter_column('news', 'text',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='Текст новости')
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Заголовок новости',
               existing_nullable=False)
    op.drop_column('news', 'link')
    op.drop_column('news', 'description')
    op.drop_column('news', 'date')
    op.drop_column('news', 'type')
    op.drop_column('news', 'image')
    op.drop_column('news', 'slug')
    op.drop_column('appointments', 'conclusion')
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('application_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('previous_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_audit_logs_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_application_audit_logs_application_id'), 'application_audit_logs', ['application_id'], unique=False)
    # ### end Alembic commands ###
    # Удаляем тип при откате
    from sqlalchemy.dialects import postgresql
    postgresql.ENUM('Анонс мероприятия', 'Отчет о мероприятии', name='newstype').drop(op.get_bind())
